version: "3.9"
services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    ports:
      - "27017:27017"

  orion:
    image: fiware/orion
    container_name: orion
    depends_on:
      - mongo
    ports:
      - "1026:1026"
    command: -dbhost mongo

  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    ports:
      - "1883:1883"

  iot-agent:
    image: fiware/iotagent-mqtt
    container_name: iot-agent
    depends_on:
      - mongo
      - orion
      - mosquitto
    environment:
      - IOTA_CB_HOST=orion
      - IOTA_CB_PORT=1026
      - IOTA_NORTH_PORT=4041
      - IOTA_REGISTRY_TYPE=mongodb
      - IOTA_LOG_LEVEL=DEBUG
      - IOTA_TIMESTAMP=true
      - IOTA_AUTOCAST=true
      - IOTA_MONGO_HOST=mongo
      - IOTA_MQTT_HOST=mosquitto
      - IOTA_MQTT_PORT=1883
    ports:
      - "4041:4041"

  simulator:
    build: ./simulator
    container_name: simulator
    depends_on:
      - iot-agent
    restart: always
